{% set version = "0.8.0" %}

package:
    name: pyoos
    version: {{ version }}

source:
    fn : pyoos-{{ version }}.tar.gz
    url: https://github.com/ioos/pyoos/archive/v{{ version }}.tar.gz
    sha256: d243e1776c88d0982fa70d986a02cbf257c54cebc7f928ba7b86ff2fc315b9b2

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - paegan
        - owslib
        - numpy
        - requests
        - fiona
        - beautifulsoup4
        - lxml

test:
    imports:
        - pyoos
        - pyoos.parsers
        - pyoos.collectors.nerrs
        - pyoos.collectors
        - pyoos.collectors.hads
        - pyoos.collectors.coops
        - pyoos.collectors.ndbc
        - pyoos.parsers.ioos
        - pyoos.collectors.usgs
        - pyoos.collectors.ioos
        - pyoos.parsers.ioos.one
        - pyoos.parsers.wqx
        - pyoos.utils
        - pyoos.collectors.awc
        - pyoos.collectors.wqp
    requires:
        - pytest

about:
    home: https://github.com/ioos/pyoos
    license: GPL-3.0
    summary: 'A Python library for collecting Met/Ocean observations.'

extra:
    recipe-maintainers:
        - ocefpaf
