travis:
  secure:
    BINSTAR_TOKEN: XumAjQpajrzTO9AB2cgp9EYnrQeDL0xk9UNfU4JIbuBzz1PZqLunOQy4SHnzi19SXJugEo4FEu4lY2JwLV/mMkYw+z6iSqxL4Eofehcw/heeHYZOOGs/nWBT887nk5pX7ZX6HwgQEtuv8qY5iDST5mHrLMKaR+zDUTVwv8B13oek/HK0qGzH3PFKhefWuHaKVAE1a869eNjqdCzteLR68LqjKneIF1lyJMSjCXX4HfDureI/rqbyBW8jK+Rl21Myf+1/q1gSe6qb1AIccRh8+fARLyuF+ZwyrDCVHcv+2DHaEZENcBJqp2V9nFTzNs8X6GU3Q+q5sTbAHaZoWqGYjw6VkqjOh9k0bnYYgOVY8v7PY+lUeN5U4ldpfRwgJ4ROhh8k6hAiWILo/QlRMow37U+titECKDQwRrgSDmFkjgRSOmaKSQqrmG/SOA0P9QWMiizuVobB3/ULK3MvJa6jorJFnn9cnvf2CKhdc7j17VhWRkK9GoQ+XhwdJORbft3FND7+2CEb2PlBT/XbJpZWuOFGN160Ybb+5Nute/9duwkzRKEUvMGJ/NgdQIciffTPfGJgpHkfZiSEaf31iymNhNu9jBac5yCVTfxxpAxh6itu9VaE4Oxbw/0Pv8ZR6jVNkfLJ7CTGJ/ut1bZkFwHBVZp2Ew5d3tLM2bbJPLtz1TQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
